version: '1.0.0'
services:
  TeCBenchAPI:
    build: .
    image: tecbench-api
    container_name: tecbench-api
    ports:
      - "5000:5000"
    volumes:
      - .:/TeCBenchAPI
  redis:
        image: redis